name: Deploy Prompt

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  run-python-script:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Show commit SHAs
        run: |
          echo "Merged commit: ${{ github.sha }}"
          echo "PR base: ${{ github.event.pull_request.base.sha }}"
          echo "PR head: ${{ github.event.pull_request.head.sha }}"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get diff files from main
        id: diff
        run: |
          git diff --name-only --diff-filter=AM ${{ github.event.pull_request.base.sha }} ${{ github.sha }} prompts/ > diff.txt
          cat diff.txt

      - name: Run script
        env:
          LANGFUSE_HOST: ${{ secrets.LANGFUSE_HOST }}
          LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
        run: |
          source venv/bin/activate
          while read file; do
            echo "Running on $file"
            PYTHONPATH=. python deploy/create_or_update_prompt.py $file
          done < diff.txt
